In [22]:
 #Q1 Write a Python program to create an array of 5 integers and display the array items. 
    # Access individual element through indexes
import numpy as np #Import numpy with an alias of np
    
arr = np.array([1,2,3,4,5]) #Creating an array

#for x in arr:
#    print(x)

for x in range(5): #Loop to call each index in first element
    print(arr[x])

1
2
3
4
5


In [83]:
#Q2 Write a Python program to reverse the order of the items in the array

#Function that reverses order by using slicing
def reverse(arrayO):
    result = arrayO[::-1]#reverse the order of array and store it into result
    
    return result
    
print(reverse(arr)) #Use function to get reverse order


[5 4 3 2 1]


In [84]:
#Q3 Create a 4X2 integer array and Prints its attributes 
#The shape of an array.
#Array dimensions.
#The Length of each element of the array in bytes.

#Function that takes an array and provides the dimension, shape, and length of the array.
def att_print(arrayO):
    print("Dim:",arrayO.ndim)#Returns dimension
    print("Shape:", arrayO.shape)#Returns Shape
    print("Length:", arrayO.itemsize)#Returns length in bytes


arr2 = np.array([[1,2], [3,4], [5,6],[7,8]])#Declare array
att_print(arr2)#Use function to print attributes
arr2

Dim: 2
Shape: (4, 2)
Length: 4


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [82]:
#Q4 return array of items in the third column from all rows in the following numpy array
# ([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

arr3 = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) #Creating array
print(arr3[:,2])#Use slicing to grab all elements and print out index 2 of each dimension


[33 66 99]


In [78]:
#Q5 Create a result array by adding the following two NumPy arrays
# arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
# arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

arrayThree = np.add(arrayOne, arrayTwo) #Call add method to combine both numpy arrays
arrayThree

array([[20, 39, 33],
       [25, 25, 28]])

In [49]:
#Q6 Sort the previous array
arrayThree.sort() #Call sort method to sort the array
arrayThree

array([[ 5,  6,  9],
       [18, 21, 27],
       [15, 24, 33],
       [ 1,  4,  7]])